### ISSUE TITLE
DoesNot Exits 

### ISSUE THREAD

**Issue by sagoyanfisic** [openedx-unsupported/ecommerce#1051]
DoesNotExist: Site matching query does not exist.

> Traceback (most recent call last):
>   File "/home/msalinas/Documentos/PRE/env_ec/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 223, in get_response
>     response = middleware_method(request, response)
>   File "/home/msalinas/Documentos/PRE/env_ec/local/lib/python2.7/site-packages/django/contrib/flatpages/middleware.py", line 11, in process_response
>     return flatpage(request, request.path_info)
>   File "/home/msalinas/Documentos/PRE/env_ec/local/lib/python2.7/site-packages/django/contrib/flatpages/views.py", line 35, in flatpage
>     site_id = get_current_site(request).id
>   File "/home/msalinas/Documentos/PRE/env_ec/local/lib/python2.7/site-packages/django/contrib/sites/shortcuts.py", line 15, in get_current_site
>     return Site.objects.get_current(request)
>   File "/home/msalinas/Documentos/PRE/env_ec/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 62, in get_current
>     return self._get_site_by_request(request)
>   File "/home/msalinas/Documentos/PRE/env_ec/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 46, in _get_site_by_request
>     site = self.get(domain__iexact=host)
>   File "/home/msalinas/Documentos/PRE/env_ec/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/home/msalinas/Documentos/PRE/env_ec/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
>     self.model._meta.object_name
> DoesNotExist: Site matching query does not exist

**Comment by vkaracic** [comment]
Have you created a new site for your ecommerce instance?
http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/open-release-eucalyptus.master/ecommerce/install_ecommerce.html#configure-a-site-partner-and-site-configuration

**Comment by clintonb** [comment]
Closing due to inactivity.
