### ISSUE TITLE
Site has no siteconfiguration.

### ISSUE THREAD

**Issue by sagoyanfisic** [openedx-unsupported/ecommerce#1065]
2016-12-23 12:34:04,330 ERROR 6972 [django.request] /home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/core/handlers/base.py:256 - Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    with context.bind_template(self):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/template/context.py", line 241, in bind_template
    updates.update(processor(self.request))
  File "/home/msalinas/ecommerce/ecommerce/ecommerce/core/context_processors.py", line 6, in core
    'lms_base_url': get_lms_url(),
  File "/home/msalinas/ecommerce/ecommerce/ecommerce/core/url_utils.py", line 71, in get_lms_url
    site_configuration = _get_site_configuration()
  File "/home/msalinas/ecommerce/ecommerce/ecommerce/core/url_utils.py", line 21, in _get_site_configuration
    return request.site.siteconfiguration
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 480, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: Site has no siteconfiguration.
2016-12-23 12:34:04,330 ERROR 6972 [django.request] /home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/core/handlers/base.py:256 - Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    with context.bind_template(self):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/template/context.py", line 241, in bind_template
    updates.update(processor(self.request))
  File "/home/msalinas/ecommerce/ecommerce/ecommerce/core/context_processors.py", line 6, in core
    'lms_base_url': get_lms_url(),
  File "/home/msalinas/ecommerce/ecommerce/ecommerce/core/url_utils.py", line 71, in get_lms_url
    site_configuration = _get_site_configuration()
  File "/home/msalinas/ecommerce/ecommerce/ecommerce/core/url_utils.py", line 21, in _get_site_configuration
    return request.site.siteconfiguration
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 480, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: Site has no siteconfiguration.
2016-12-23 12:34:04,330 ERROR 6972 [django.request] /home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/core/handlers/base.py:256 - Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    with context.bind_template(self):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/template/context.py", line 241, in bind_template
    updates.update(processor(self.request))
  File "/home/msalinas/ecommerce/ecommerce/ecommerce/core/context_processors.py", line 6, in core
    'lms_base_url': get_lms_url(),
  File "/home/msalinas/ecommerce/ecommerce/ecommerce/core/url_utils.py", line 71, in get_lms_url
    site_configuration = _get_site_configuration()
  File "/home/msalinas/ecommerce/ecommerce/ecommerce/core/url_utils.py", line 21, in _get_site_configuration
    return request.site.siteconfiguration
  File "/home/msalinas/ecommerce/env_ecommcerce/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 480, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: Site has no siteconfiguration

**Comment by vkaracic** [comment]
https://github.com/edx/ecommerce/issues/1051#issuecomment-266955409

**Comment by vkaracic** [comment]
Closed due to inactivity.
